name: "Run ghalint"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  ghalint:
    runs-on: ubuntu-slim
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install ghalint
        run: |
          curl -L -o ghalint.tar.gz 'https://github.com/suzuki-shunsuke/ghalint/releases/download/v1.5.4/ghalint_1.5.4_linux_amd64.tar.gz'
          tar xzf ghalint.tar.gz ghalint

      - name: Run ghalint run
        run: |
          ./ghalint run

      - name: Run ghalint act
        run: |
          ./ghalint act